version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"  # Expose the PostgreSQL port
    volumes:
      - pgdata:/var/lib/postgresql/data  # Persist datagit

  app:
    build: .
    volumes:
      - .:/app # this to automate changes in the local to the conatiner
    ports:
      - "8000:8000"
    depends_on:
      - db  # Ensure the app starts after the database is ready
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
    env_file:
      .env
# Correctly positioned volumes section
volumes:
  pgdata: {}  # Define a volume to persist PostgreSQL data
